// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

namespace Migrations.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210310041504_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Models.AcademicInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("AcademicInfos");
                });

            modelBuilder.Entity("Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BoardName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("Models.ExamType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AcademicInfoID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcademicInfoID")
                        .IsUnique();

                    b.ToTable("ExamTypes");
                });

            modelBuilder.Entity("Models.HscEquivalent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BoardId")
                        .HasColumnType("int");

                    b.Property<int>("ExamTypeId")
                        .HasColumnType("int");

                    b.Property<float>("GPA")
                        .HasColumnType("float");

                    b.Property<int>("HscExamNames")
                        .HasColumnType("int");

                    b.Property<int?>("PassingYearId")
                        .HasColumnType("int");

                    b.Property<string>("RegNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("ExamTypeId")
                        .IsUnique();

                    b.HasIndex("PassingYearId");

                    b.ToTable("HscEquivalents");
                });

            modelBuilder.Entity("Models.PassingYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PassingYears");
                });

            modelBuilder.Entity("Models.Programs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ProgramName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Programss");
                });

            modelBuilder.Entity("Models.SscEquivalent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BoardId")
                        .HasColumnType("int");

                    b.Property<int>("ExamTypeId")
                        .HasColumnType("int");

                    b.Property<float>("GPA")
                        .HasColumnType("float");

                    b.Property<int?>("PassingYearId")
                        .HasColumnType("int");

                    b.Property<string>("RegNumber")
                        .HasColumnType("text");

                    b.Property<int>("SscExamNames")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("ExamTypeId")
                        .IsUnique();

                    b.HasIndex("PassingYearId");

                    b.ToTable("SscEquivalents");
                });

            modelBuilder.Entity("Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FatherName")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("GuardianContactNo")
                        .HasColumnType("text");

                    b.Property<string>("GuardianName")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("MotherName")
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .HasColumnType("text");

                    b.Property<string>("PresentAddress")
                        .HasColumnType("text");

                    b.Property<int>("ProgramsId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ProgramsId")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Models.AcademicInfo", b =>
                {
                    b.HasOne("Models.Student", "Student")
                        .WithOne("AcademicInfo")
                        .HasForeignKey("Models.AcademicInfo", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.ExamType", b =>
                {
                    b.HasOne("Models.AcademicInfo", "AcademicInfo")
                        .WithOne("ExamTypes")
                        .HasForeignKey("Models.ExamType", "AcademicInfoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.HscEquivalent", b =>
                {
                    b.HasOne("Models.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId");

                    b.HasOne("Models.ExamType", "ExamType")
                        .WithOne("HscEquivalent")
                        .HasForeignKey("Models.HscEquivalent", "ExamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.PassingYear", "PassingYear")
                        .WithMany()
                        .HasForeignKey("PassingYearId");
                });

            modelBuilder.Entity("Models.SscEquivalent", b =>
                {
                    b.HasOne("Models.Board", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId");

                    b.HasOne("Models.ExamType", "ExamType")
                        .WithOne("SscEquivalent")
                        .HasForeignKey("Models.SscEquivalent", "ExamTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.PassingYear", "PassingYear")
                        .WithMany()
                        .HasForeignKey("PassingYearId");
                });

            modelBuilder.Entity("Models.Student", b =>
                {
                    b.HasOne("Models.Programs", "Programs")
                        .WithOne("Student")
                        .HasForeignKey("Models.Student", "ProgramsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
